users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register' ),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_views, name='profile'),

    path('account_details/', views.account_details, name='account_details'),
    path('edit_account_details/', views.edit_account_details, name='edit_account_details'),
    path('update_account_details/', views.update_account_details, name='update_account_details'),

    path('password_reset/', views.password_reset_request, name='password_reset_request'),
    # Юідб і токен який ми повинні були передати в посиланні
    path('password_reset/<uidb64>/<token>/', views.password_reset_confirm, name='password_reset_confirm'),

    path('account_activation_request/', views.account_activation_request, name='account_activation_request'),
    path('account_activation_confirm/<uidb64>/<token>/', views.account_activation_confirm, name='account_activation_confirm'),

]

usersguide/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('users/', include('users.urls', namespace='users')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.html import strip_tags

class CustomUserManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, username, password=None, **extra_fields): # Поля які будемо використовувати для реєстрації
        if not email:
            raise ValueError('Необхідно вказати email!')

        email = self.normalize_email(email) # Функція для валідації пошти
        user = self.model(email=email, first_name=first_name, username=username, last_name=last_name, **extra_fields)
        #  Створюється юзер, він модель. А модель має в собі поля які користувач ввів
        user.set_password(password) # Вказуємо пароль
        user.save(using=self._db) # Зберігаємо в нашу базу даних
        return user


    # Нам необхідно задати поля для створення супер юзера, бо він видаватиме помилку через те зо потребує дефолтних полів
    def create_superuser(self, email, first_name, last_name, password, username=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        #!  extra_fields це Права користувача /\

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Супер користувач повинен бути is_staff=True.')

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Супер користувач повинен бути is_superuser=True.')
        if username is None:
            username = email.split('@')[0]
        return self.create_user(email, first_name, username, last_name, password, **extra_fields)


class CustomUser(AbstractUser):
    email = models.EmailField(unique=True, verbose_name='Email', max_length=100)
    first_name = models.CharField(verbose_name='Ім`я', max_length=100)
    last_name = models.CharField(verbose_name='Прізвище', max_length=100)
    username = models.CharField(verbose_name='Нікнейм', max_length=150, unique=True)
    phone = models.CharField(verbose_name='Номер телефону', max_length=15, blank=True, null=True)

    address1 = models.CharField(verbose_name='Адреса', max_length=255, blank=True, null=True) #  null=True щоб в БД була пуста клітинка
    address2 = models.CharField(verbose_name='Вулиця', max_length=255, blank=True, null=True) #  null=True щоб в БД була пуста клітинка
    city = models.CharField(verbose_name='Місто', max_length=255, blank=True, null=True)
    country = models.CharField(verbose_name='Країна', max_length=150, blank=True, null=True)
    province = models.CharField(verbose_name='Область', max_length=255, blank=True, null=True)
    postal_code = models.CharField(verbose_name='Поштовий код', max_length=15, blank=True, null=True)
    marketing_consent1 = models.BooleanField(default=False) # Розсилка на рекламу
    marketing_consent2 = models.BooleanField(default=False)

    email_confirmed = models.BooleanField(default=False)

    """
     За замовчуванням якщо ми навіть створимо модель, Джанго потребуватиме нікнейм для реєстрації 
     Для того щоб зробити реєстрацію по пошті
     """

    objects = CustomUserManager() # Ініціалізуємо для

    USERNAME_FIELD = 'email' # Необхідно взяти юзернейм і помііняти на емейл, Щоб джанго в своїй моделі замінив юзернейм на емейл який нам необхіно використати
    REQUIRED_FIELDS = ['first_name', 'last_name'] # Посторонні поля які будуть використовувати для реєстрації (Ми їх хлчемо бачити в реєстрації)

    def __str__(self):
        return self.email

    def clean(self):
        # Метод clean() у моделі викликається перед збереженням об'єкта
        for field in ['phone', 'address1', 'address2', 'city', 'country', 'province',
                      'postal_code']:  # Проходимося по всіх полях, які можуть містити текст
            value = getattr(self, field)
            # Отримуємо значення поля з об'єкта моделі
            if value:
                # Якщо поле не порожнє
                setattr(self, field, strip_tags(value))
                # Очищаємо значення від HTML і записуємо назад у модель

users/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from .forms import CustomUserLoginForm, CustomUserUpdateForm, CustomUserCreationForm, PasswordResetRequestForm, PasswordResetConfirmForm
from .models import CustomUser

# New
from .tasks import send_welcome_email, send_password_reset_email, send_account_activation_email
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_decode
from django.utils.encoding import force_str
import logging

from .tokens import account_activation_token


def register(request):
    if request.method == 'POST': # Перевіряємо на пост запит. Спрацьовуватиме тоді коли буде пост запит
        form = CustomUserCreationForm(request.POST) # Ініціалізуємо запит. реквест пост дані які він нам дав
        if form.is_valid(): #Даними ми форму заповнили. Якщо форма валідна. Валідації які ми прописували
            user = form.save() # Зберігаємо користувача
            user.email_confirmed = False # Вказуємо що пошта не активована
            user.save()
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            # логінимо збереженого користувача і передаємо бекенд для того щоб запобігти конфліктів з дефолтним бекендом

            send_welcome_email.delay(user.email, user.first_name) # Відправляємо повідомлення. В таску передали пошту і ім'я

            return redirect('users:profile')  # Редіректимо на профіль
    else:
        form = CustomUserCreationForm() # Якщо форма не валідна. Виводимо пусту форму і помилки
    return render(request, 'users/register.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = CustomUserLoginForm(request=request, data=request.POST) # Дата це дані які заповнюють
        if form.is_valid():
            user = form.get_user() # В юзер переміщуємо користувача. Стандартна перевірка джанго яка дістає користувача який є в системі

            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('users:profile')
    else:
        form = CustomUserLoginForm()
    return render(request, 'users/login.html', {'form': form})

@login_required
def profile_views(request): # Для перегляду профіля

    return render(request, 'users/profile.html', {'user': request.user}) # Передаємо в контекст даного юзера

# Представлення для htmx. Яке динамічно міняє контент сторінки без перезагрузки роблячи запити до серверу
@login_required
def account_details(request):
    user = CustomUser.objects.get(id=request.user.id) # Беремо дані поточного користувача
    return render(request, 'users/partials/account_details.html', {'user': user})

@login_required
def edit_account_details(request):
    form = CustomUserUpdateForm(instance=request.user)
    return render(request, 'users/partials/edit_account_details.html',
                  {'user': request.user, 'form': form})


@login_required
def update_account_details(request):
    if request.method == 'POST':
        form = CustomUserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            user = form.save(commit=False)
            user.clean()
            user.save()
            return render(request, 'users/partials/account_details.html', {'user': user})
        else:
            return render(request, 'users/partials/edit_account_details.html', {'user': request.user, 'form': form})
    return render(request, 'users/partials/account_details.html', {'user': request.user})

def logout_view(request):
    logout(request)
    return redirect('users:login')



def password_reset_request(request): # Надіслати запит на зміну пароля
    if request.method == 'POST': # Якщо надсилаємо форму
        form = PasswordResetRequestForm(request.POST) # Ініціалізуємо форму з даними
        if form.is_valid(): # Якщо дані валідні
            email = form.cleaned_data['email'] # Беремо пошту з очищених даних з ініціалізованої форми
            user = CustomUser.objects.filter(email=email).first() # Беремо користувача який це надіслав за допомогою пошти яку ми взяли вище
            if user: # Якщо такий користувач існує
                logging.info(f'Attempting to send password reset email to {email}, for user id {user.pk}') # Логуємо початок

                send_password_reset_email.delay(email, user.pk) # Запускаємо таску на пошту, передаючи емейл і ід користувача

                messages.success(request, 'Скидання пароля в черзі. Будь ласка, перевірте свою поштову скриньку для того щоб скинути пароль.')
                # Повідомлення відправлено очікуйте для користувача
                return render(request, 'users/password_reset_done.html', {'email': email})  # Рендеримо сторінку на якій буде повідомлення представленне вище
            else:
                messages.warning(request, 'Не знайдено акаунта для цієї пошти.') # Нема акаунта повідомлення
        else:
            messages.warning(request, 'Введіть правильну електронну адресу.') # Неправильно заповнена форма
    else:
        form = PasswordResetRequestForm() # Ініціалізація для сторінки, та сама сторінка х переданим контекстом форми
    return render(request, 'users/password_reset_request.html', {'form': form})


def password_reset_confirm(request, uidb64, token): # Коли користувач перейшов за посиланням видачі нового пароля
    # Приймаємо запит, юідб64 і токен який є в тасці. Перейшов по посиланню, ми по цьому посиланню приймаємо ці 2 елемента
    # Які згенеровані для користувача і відправлені в вигляді посилання на пошту
    try: # Пробуємо співставити нашого користувача. "Чи правда що це та людина"
        uid = force_str(urlsafe_base64_decode(uidb64)) # Розшифровуємо юід яке відправляли зашифроване
        user = CustomUser.objects.get(pk=uid) # Перевіряємо чи є такий в нашій БД
    except (TypeError, ValueError, OverflowError, CustomUser.DoesNotExist):
        user = None # Якщо нема то так і записуємо

    # Якщо користувач є і перевіряємо користувача і його токен, якщо вони співпадають
    if user is not None and default_token_generator.check_token(user, token):
        if request.method == 'POST':
            form = PasswordResetConfirmForm(request.POST)
            if form.is_valid():
                user.set_password(form.cleaned_data['new_password1']) # Встановлюємо новий пароль, який користувач ввів
                user.save() # Зберігаємо користувача
                messages.success(request, 'Ваш пароль змінено успішно!') # Вивід повідомлення користувачу
                return render(request, 'users/password_reset_complete.html') # Повертаємо сторінку з успішним повідомленням
        else:
            form = PasswordResetConfirmForm() # На початкову сторінку, зарендеримо сторінку і форми
        return render(request, 'users/password_reset_confirm.html', {'form': form, 'validlink': True})
    else:
        # Якщо користувач не знайшовся. Якщо валід лінк фалсе виведемо повідомлення що посилання не валідне
        return render(request, 'users/password_reset_confirm.html', {'validlink': False})

@login_required
def account_activation_request(request):
    if request.method == 'POST': # Жмемо кнопку
            email = request.user.email # Беремо пошту
            user = request.user
            if user: # Якщо такий користувач існує
                if user.email_confirmed:
                    messages.info(request, "Email вже підтверджено.")
                    return redirect('users:profile')


                logging.info(f'Attempting to send acctivation email to {email}, for user id {user.pk}') # Логуємо початок
                send_account_activation_email.delay(email, user.pk) # Запускаємо таску на пошту, передаючи емейл і ід користувача
                messages.success(request, f'Лист активації акаунта надіслано на пошту {email}. Перевірте свою пошту та перейдіть за посиланням в листі')
                # Повідомлення відправлено очікуйте для користувача
                return redirect('users:profile')
            else:
                messages.warning(request, 'Не знайдено акаунта для цієї пошти.') # Нема акаунта повідомлення
    return redirect('users:profile')


def account_activation_confirm(request, uidb64, token):
    # Приймаємо запит, юідб64 і токен який є в тасці. Перейшов по посиланню, ми по цьому посиланню приймаємо ці 2 елемента
    # Які згенеровані для користувача і відправлені в вигляді посилання на пошту
    try:  # Пробуємо співставити нашого користувача. "Чи правда що це та людина"
        uid = force_str(urlsafe_base64_decode(uidb64))  # Розшифровуємо юід яке відправляли зашифроване
        user = CustomUser.objects.get(pk=uid)  # Перевіряємо чи є такий в нашій БД
    except (TypeError, ValueError, OverflowError, CustomUser.DoesNotExist):
        user = None  # Якщо нема то так і записуємо

    # Якщо користувач є і перевіряємо користувача і його токен, якщо вони співпадають
    if user is not None and account_activation_token.check_token(user, token):
                if user.email_confirmed:
                    messages.info(request, "Email вже підтверджено.")
                    return redirect('users:profile')

                user.email_confirmed = True  # Вказуємо що пошта не активована
                user.save(update_fields=["email_confirmed"])  # Зберігаємо користувача
                messages.success(request, 'Акаунт успішно активований!')  # Вивід повідомлення користувачу
                return redirect('users:profile')  # Повертаємо сторінку з успішним повідомленням
    else:
        # Якщо користувач не знайшовся. Якщо валід лінк фалсе виведемо повідомлення що посилання не валідне
        return render(request, 'users/password_reset_confirm.html', {'validlink': False})

users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/htmx.org@2.0.8/dist/htmx.min.js"></script>
</head>
<body>


<main class="container my-4">

    {% block content %}
    {% endblock content %}
</main>
</body>
</html>

users/templates/users/login.html
{% extends 'users/base.html' %}

{% block title %}Вхід{% endblock %}

{% block content %}
{% if user.is_authenticated %}
    <p class="reg-form">Ви вже авторизовані!</p>
{% else %}
<h1> Увійти </h1>
<form method="post" class="reg-form">
    {% csrf_token %}
    <div class="form-group">
        <label for="{{ form.username.id_for_label }}"> Електронна пошта </label>
        {{ form.username }}
        {% if form.username.errors %}
            <div class="error">{{ form.username.errors }}</div>
        {% endif %}
    </div>

    <div class="form-group">
        <label for="{{ form.password.id_for_label }}"> Пароль </label>
        {{ form.password }}
        {% if form.password.errors %}
            <div class="error">{{ form.password.errors }}</div>
        {% endif %}
    </div>


    <button type="submit" > Увійти </button>


    <p> Не маєте акаунту? <a href="{% url 'users:register' %}" class="link"> Зареєструватись </a> </p>
    <p> Забули пароль? <a href="{% url 'users:password_reset_request' %}" class="link"> Скинути пароль </a> </p>
{% endif %}
</form>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'users/base.html' %}

{% block title %} {% endblock %}

{% block content %}
<h1>Пароль успішно змінено</h1>
<p> Можете повернутись в аккаунт <a href="{% url 'users:login' %}" class="link"> Увійти </a> </p>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'users/base.html' %}

{% block title %} Скидання паролю {% endblock %}

{% block content %}
  <h1>Скинути пароль</h1>
  {% if validlink %}
    <p>Введіть новий пароль</p>
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <div class="{{ message.tags }}">{{ message }}</div>
            {% endfor %}
        </div>
    {% endif %}

    <form method="post" class="reg-form">
        {% csrf_token %}
        <div class="form-group">
          <label for="{{ form.new_password1.id_for_label }}"> Пароль </label>
          {{ form.new_password1 }}
          {% if form.new_password1.errors %}
              <div class="error">{{ form.new_password1.errors }}</div>
          {% endif %}
      </div>

      <div class="form-group">
          <label for="{{ form.new_password2.id_for_label }}"> Повторіть пароль </label>
          {{ form.new_password2 }}
          {% if form.new_password2.errors %}
              <div class="error">{{ form.new_password2.errors }}</div>
          {% endif %}
      </div>
        <button type="submit" class="btn-success">Змінити пароль</button>

    </form>
  {% else %}
  <p>Посилання скидання пароля зламане. Ви можете створити нове</p>
  <a href="{% url 'users:password_reset_request' %}" class="link"> Скинути пароль </a>
  {% endif %}
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'users/base.html' %}

{% block title %} Скидання паролю {% endblock %}

{% block content %}
<h1>Посилання скидання паролю відправлено!</h1>
<p>Будь ласка, перевірте свою електронну пошту <b>{{ email }}</b> або розділ "спам"</p>
<p> Повернутись до авторизації <a href="{% url 'users:login' %}" class="link"> Логін </a> </p>
{% endblock %}

users/templates/users/password_reset_request.html
{% extends 'users/base.html' %}

{% block title %} Скинути пароль {% endblock %}

{% block content %}
<h1>Скинути пароль</h1>
<p>Напишіть свій email і отримайте посилання для скидання пароля</p>
{% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div class="{{ message.tags }}">{{ message }}</div>
        {% endfor %}
    </div>
{% endif %}

<form method="post" class="reg-form">
    {% csrf_token %}
    <div class="form-group">
        <label for="{{ form.email.id_for_label }}">Email *</label>
        {{ form.email }}
        {% if form.email.errors %}
            <div class="text-danger small">{{ form.email.errors }}</div>
        {% endif %}
    </div>
    <button type="submit" class="btn-success">Надіслати</button>
    <p> Повернутись до авторизації <a href="{% url 'users:login' %}" class="link"> Логін </a> </p>
</form>

{% endblock %}

users/templates/users/profile.html
{% extends 'users/base.html' %}

{% block title %}Ваш профіль{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<h1 > Привіт! {{ request.user.first_name|upper }} {{ request.user.last_name|upper }} </h1>
<div class="profile-section">

     {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <div class="{{ message.tags }}">{{ message }}</div>
            {% endfor %}
        </div>
    {% endif %}



    <p class="default-address"><h2>Детальніше</h2></p>
    <p><strong>Ім'я:</strong> {{ user.first_name }},  {{ user.last_name }}</p>
    <p><strong>Email:</strong> {{ user.email }}</p>
    <p><strong>Тег:</strong> @{{ user.username }}</p>
    <p><strong>Номер телефону: </strong>{{ request.user.phone|default:"Невідомий" }}</p>
    <p><strong>Країна: </strong>{{ request.user.country|default:"Не обрано" }}</p>
    <strong>Активація акаунту:</strong>
        {% if request.user.email_confirmed %}
            ✅ Підтверджено
        {% else %}
            ❌ Не підтверджено
            <form method="post" action="{% url 'users:account_activation_request' %}">
                {% csrf_token %}
                 <button type="submit"> Активувати </button>
            </form>
        {% endif %}

    <br>
    <hr>
    <br>
    <div id="profile-content">
                {% include 'users/partials/account_details.html' %}
    </div>
<!--    <button hx-get="{% url 'users:edit_account_details' %}"-->
<!--                hx-target="#account-details-content"-->
<!--                hx-swap="innerHTML">-->
<!--        Змінити-->
<!--    </button>-->
    <br>
    <br>

    <div id="account-details-content"></div>
    <form method="post" action="{% url 'users:logout' %}">
        {% csrf_token %}
         <button type="submit"> Вийти </button>
    </form>

</div>
{% endif %}
{% endblock %}

users/templates/users/register.html
{% extends 'users/base.html' %}

{% block title %}Реєстрація{% endblock %}

{% block content %}
{% if user.is_authenticated %}
    <p class="reg-form">Ви вже авторизовані!</p>
{% else %}
<h1>Зареєструватися</h1>
<form method="post" class="reg-form">
    {% csrf_token %}
    <div class="form-group">
        <label for="{{ form.first_name.id_for_label }}"> Ім'я </label>
        {{ form.first_name }}
        {% if form.first_name.errors %}
            <div class="error">{{ form.first_name.errors }}</div>
        {% endif %}
    </div>
    
    <div class="form-group">
        <label for="{{ form.last_name.id_for_label }}"> Прізвище </label>
        {{ form.last_name }}
        {% if form.last_name.errors %}
            <div class="error">{{ form.last_name.errors }}</div>
        {% endif %}
    </div>
    
    <div class="form-group">
        <label for="{{ form.email.id_for_label }}"> Електронна пошта </label>
        {{ form.email }}
        {% if form.email.errors %}
            <div class="error">{{ form.email.errors }}</div>
        {% endif %}
    </div>
    
    <div class="form-group">
        <label for="{{ form.username.id_for_label }}"> Тег </label>
        {{ form.username }}
        {% if form.username.errors %}
            <div class="error">{{ form.username.errors }}</div>
        {% endif %}
    </div>
    
    <div class="form-group">
        <label for="{{ form.password1.id_for_label }}"> Пароль </label>
        {{ form.password1 }}
        {% if form.password1.errors %}
            <div class="error">{{ form.password1.errors }}</div>
        {% endif %}
    </div>
    
    <div class="form-group">
        <label for="{{ form.password2.id_for_label }}"> Повторіть пароль </label>
        {{ form.password2 }}
        {% if form.password2.errors %}
            <div class="error">{{ form.password2.errors }}</div>
        {% endif %}
    </div>

    <div class="checkbox-group">
        <label for="{{ form.marketing_consent1.id_for_label }}"> Я погоджуюсь на отримання рекомендацій </label>
        {{ form.marketing_consent1 }}
        {% if form.marketing_consent1.errors %}
            <div class="error">{{ form.marketing_consent1.errors }}</div>
        {% endif %}
    </div>

    <div class="checkbox-group">
        <label for="{{ form.marketing_consent2.id_for_label }}"> Я погоджуюсь на отримання персональних рекомендацій </label>
        {{ form.marketing_consent2 }}
        {% if form.marketing_consent2.errors %}
            <div class="error">{{ form.marketing_consent2.errors }}</div>
        {% endif %}
    </div>

    <button type="submit" > Зареєструватися </button>
    <p> Вже маєте аккаунт? <a href="{% url 'users:login' %}" class="link"> Увійти </a> </p>
    
</form>
{% endif %}
{% endblock %}